### ISSUE TITLE
Can’t get response body size

### ISSUE THREAD

**Issue by naoki-akimoto** [KiiPlatform/KiiThingSDK-Embedded-Core#49]
現在のkii_core_tにはレスポンスの実際のサイズを返すフィールドが存在しません。
HttpレスポンスでのContent-Lengthの値を返すようなフィールドが必要では無いでしょうか？
実際のサイズが分からないとresponse_bodyをどこまで読めばよいかなどが分かりません。
検討をお願いします。

**Comment by shinsuke-nara** [comment]
response_body をヌル終端にするよう指定しましたので、この問題は解決済みです。
