### ISSUE TITLE
Add small tests.

### ISSUE THREAD

**Issue by naoki-akimoto** [KiiPlatform/KiiThingSDK-Embedded-Core#61]
スモールテスト(ユニットテスト)を追加してください。

**Comment by shinsuke-nara** [comment]
ポイントは、送信メッセージのチェックです。

**Comment by naoki-akimoto** [comment]
https://github.com/KiiPlatform/KiiThingSDK-Embedded/issues/98 でEmbedded側に移動させたのでこちらは閉じます。
