### ISSUE TITLE
Should KII_SOCKET_MAX_BUFF_SIZE be removed?

### ISSUE THREAD

**Issue by shinsuke-nara** [KiiPlatform/KiiThingSDK-Embedded-Core#69]
KII_SOCKET_MAX_BUFF_SIZEというマクロが有ります。ソケットが利用するバッファのサイズを規定する為に存在していたようです。ただし、現在このマクロを使ってバッファサイズを規定していない様に見えます。

KII_SOCKET_MAX_BUFF_SIZEを利用する事が潜在的なバグになっている可能性があるので、この点を調査し、必要ならば修正をお願いします。

**Comment by naoki-akimoto** [comment]
このマクロ定義自体はソケットと最大何バイト渡す・受けるかを定義するものです。バッファなどを用意するための定義では無いので利用自体は問題無いと思われます。
